# general configs
projectName : labCollab
tag : basicModel-biGRU-FirstRoundOptimization
# run specific configs
wandb : True
lr : 0.001
num_layers : 1
pos_weight : 3.0
fold : 0
num_gpus : 1
batch_size : 1000
max_epochs : 400
num_workers : 5