# general configs
projectName : labCollab
tag : optimizationRound1-ANN-sweepHiddenSize
# run specific configs
wandb : True
baseModel : TRANSFORMER # Choices are ANN, GRU, LSTM, TRANSFORMER
lr : 0.0001 # optimization 1 (0.00001, 0.00003, 0.0001, 0.0003, 0.001, 0.003, 0.01, 0.03, 0.1, 0.3)
pos_weight : 3.0 # optimization 2 (0.25, 0.5, 1.0, 2.0, 4.0, 8.0)
num_layers : 2 # optimization 3 (2 to 10)
hidden_size : 32 # optimization 4 (4, 8, 16, 32, 64, 128, 256)
fold : 0 # Validation
test : 1 # for unseen test set
num_gpus : 1
batch_size : 500
max_epochs : 500
num_workers : 5