wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.9
    code_path: code/110_basicModel02.py
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    m:
    - 1: trainer/global_step
      6:
      - 3
    - 1: valid_totalLoss_step
      5: 1
      6:
      - 1
    - 1: valid_totalLoss_epoch
      5: 1
      6:
      - 1
    - 1: valid_class_accuracy
      5: 1
      6:
      - 1
    - 1: valid_class_AUROC
      5: 1
      6:
      - 1
    - 1: epoch
      5: 1
      6:
      - 1
    - 1: train_totalLoss_epoch
      5: 1
      6:
      - 1
    - 1: train_totalLoss_step
      5: 1
      6:
      - 1
    python_version: 3.10.0
    start_time: 1679263892.859776
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      2:
      - 1
      - 9
      - 41
      - 55
      3:
      - 7
      - 13
      - 15
      - 23
      4: 3.10.0
      5: 0.13.9
      8:
      - 2
      - 5
batch_size:
  desc: null
  value: 1000
fold:
  desc: null
  value: 0
lr:
  desc: null
  value: 0.0003
max_epochs:
  desc: null
  value: 400
num_gpus:
  desc: null
  value: 1
num_layers:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 5
pos_weight:
  desc: null
  value: 3.0
projectName:
  desc: null
  value: labCollab
tag:
  desc: null
  value: basicModel-biGRU-AMIAabstract
wandb:
  desc: null
  value: true
